> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# NumPy Module


### Introduction
NumPy stands for Numerical python and is used for numerical data processing and is the foundational package for mathematical computing. NumPy provides a large number of mathematical function, which are called Universal Functions or ufunc.These functions operate element-wise on an array, and create another array as the output.

Some of these functions are listed below:

* ravel
* mean
* hstack
* transpose
* trace

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ishit239/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ishit239/numpy-array-operations


'https://jovian.ai/ishit239/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [32]:
# List of functions explained 
function1 = np.ravel
function2 = np.mean
function3 = np.hstack
function4 = np.transpose
function5 = np.copyto

## Function 1 - np.racel

This function flattens the dataset into a single row

In [12]:
# Example 1 
arr = np.array([[10,15,26,23,14,45],
                [12,45,47,56,87,13]])
y=np.ravel(arr)
y

array([10, 15, 26, 23, 14, 45, 12, 45, 47, 56, 87, 13])

The above example shows how its flatten the data into single row i.e From 2-D to 1-D

In [13]:
# Example 2 
arr_1 = np.array([[[10,15,17,26],
                  [12,15,16,45],
                  [21,45,15,64]]])
np.ravel(arr_1,order='F')

array([10, 12, 21, 15, 15, 45, 17, 16, 15, 26, 45, 64])

In the above example the order F means the index order will be column-major. it is also known as Fortran Style

In [15]:
# Example 3 
arr_2 = [[1, 2], 
        [3, 4,6]]
np.ravel(arr_2)

/opt/conda/lib/python3.9/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)


array([list([1, 2]), list([3, 4, 6])], dtype=object)

In the above example, the function does not flatten the datasets as the size of the array is not same in the index 0 and 1. To fix this we have to make the array to equal size.

End

In [16]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ishit239/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ishit239/numpy-array-operations


'https://jovian.ai/ishit239/numpy-array-operations'

## Function 2 - np.mean

It is used to find the mean value of the NumPy array

In [17]:
# Example 1 - working
arr = np.array([[2,4,8,9,7,3],
               [11,85,44,21,14,25]])
np.mean(arr)

19.416666666666668

It is used to find the mean value of the NumPy array

In [18]:
# Example 2 
arr = np.array([[2,4,8,9,7,3],
               [11,85,44,21,14,25]])
np.mean(arr, axis = 0)

array([ 6.5, 44.5, 26. , 15. , 10.5, 14. ])

Compute the arithmetic mean (average) of the given data (array elements) along the specified axis.

In [19]:
# Example 3 - 
arr = arr = np.array([[2,4,8,9,7,3],
               [11,85,44,21,14,25]])
np.mean(arr, axis = 7)

AxisError: axis 7 is out of bounds for array of dimension 2

It breaks because there is no axis 7

Its a nice math performing function

In [20]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ishit239/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ishit239/numpy-array-operations


'https://jovian.ai/ishit239/numpy-array-operations'

## Function 3 - np.hstack

This function stacks two arrays together.

In [21]:
# Example 1 - working
arr_s1 = np.array([11,12,13,14,15])

arr_s2 = np.array([21,22,23,24,25])

np.hstack((arr_s1,arr_s2))

array([11, 12, 13, 14, 15, 21, 22, 23, 24, 25])

In the above example, the function stacks the two array together to form a single array.

In [22]:
# Example 2 - working
arr_s = np.array([[1,2,3],
                   [4,5,6]])

arr_ss = np.array([[7,8,9],
                   [10,11,12]])

np.hstack((arr_s,arr_ss))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In the above example, the function stacks the two array together index wise and form a single array.

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
arr_1 = np.array([[[1,2,3,],
                  [4,5,6],
                  [7,8,9]]])

arr_2 = np.array([[11,12,13],
                  [14,15,16],
                  [17,18,19]])
np.hstack((arr_1,arr_2))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In the above example, both the arrays have different dimensions. To stack the arrays all the arrays that are being stacked should have equal dimensions.

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ishit239/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ishit239/numpy-array-operations


'https://jovian.ai/ishit239/numpy-array-operations'

## Function 4 - np.transpose

The transpose function helps us to interchange rows as columns, and vice-versa.

In [26]:
# Example 1 - working
arr_t = np.array([[73,71,57,63],
                  [64,98,81,45]])

np.transpose(arr_t)

array([[73, 64],
       [71, 98],
       [57, 81],
       [63, 45]])

In the above example, the rows element are interchanged to the columns elements.

In [27]:
# Example 2 - working
arr_t1 = np.array([[12,74,16],
                   [18,27,22],
                   [24,26,88]])

np.transpose(arr_t1)

array([[12, 18, 24],
       [74, 27, 26],
       [16, 22, 88]])

In the above example, the rows element are interchanged to the columns elements.

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
arr_t2 = np.array([[[50,12,14],
                   [29,46,61],
                   [21,23,34]]])

arr_t3 = np.array([[[19,12,13],
                   [14,18,16],
                   [17,18,19]]])

np.transpose(arr_t2,arr_t3)

TypeError: only integer scalar arrays can be converted to a scalar index

Explanation about example (why it breaks and how to fix it)In the above example, the function does not works as in the argument two arrays are given and only one is required as the transpose function works on scalar arrays to transpose it.



To fix this we need to give the scalar array in the argument.

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ishit239/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ishit239/numpy-array-operations


'https://jovian.ai/ishit239/numpy-array-operations'

## Function 5 - np.copyto

It used to copies the values of one array to another array

In [35]:
# Example 1

arr1 = np.array([1,4,5])
arr2 = [3,4,5]
np.copyto(arr1, arr2)
print(arr1)

[3 4 5]


here after using copyto function arr2 is get copy to arr1

In [38]:
# Example 2 - 
arr1 = np.array([[1,4,5],[2,3,4]])
arr2 = [[2,3,4],[3,4,5]]
np.copyto(arr1, arr2)
print(arr1)

[[2 3 4]
 [3 4 5]]


Here 2-d arr2 is  copy to 2-d arr1

In [39]:
# Example 3 - 
arr1 = np.array([[1,4,5],[2,3,4]])
arr2 = [[2,3,4],[3,4,5],[8,3,4]]
np.copyto(arr1, arr2)
print(arr1)

ValueError: could not broadcast input array from shape (3,3) into shape (2,3)

In this the shape of the both array is not equal hence both are not executing to solve it we have make both array shape equal column and equal row

This function mainly used copy from different array to specific array

In [40]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ishit239/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ishit239/numpy-array-operations


'https://jovian.ai/ishit239/numpy-array-operations'

## Conclusion

Functions that we covered in this notebook

- np.ravel()

- np.nean()

- np.hstack()

- np.transpose()

- np.copyto()

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [41]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ishit239/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/ishit239/numpy-array-operations


'https://jovian.ai/ishit239/numpy-array-operations'